# Generated by Django 5.2.15 on 2026-06-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.IntegerField(default=0)),
                ('awaiting_reply_since', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('content_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat.contentmodel')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat.fan')),
            ],
            options={
                'unique_together': {('fan', 'content_model')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('fan', 'Fan'), ('chatter', 'Chatter')], max_length=10)),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('text', 'Text'), ('ppv', 'PPV')], default='text', max_length=10)),
                ('ppv_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_msg_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'id'], name='message_conv_id_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_msg_id__isnull', False)), fields=('conversation', 'client_msg_id'), name='unique_conversation_client_msg_id'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'text'), ('ppv_price__isnull', True)), models.Q(('kind', 'ppv'), ('ppv_price__gt', 0), ('ppv_price__isnull', False)), _connector='OR'), name='ppv_price_check')],
            },
        ),
    ]
